spring.application.name=springboot-jpa-crud
server.port=8090
server.servlet.context-path=/api/v1
spring.datasource.url=jdbc:mysql://localhost:8090/3607/spring_jpa_crud
spring.datasource.username=root
spring.datasource.password=1234
